/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;

/**
 *
 * @author programmer
 */
public class LoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form LoginWindow
     */
    
    String userName;
    char passWord[];
    String fileName="PlayersList.txt";
    FileReader fileReader;
    FileWriter fileWriter;
    BufferedReader ReadPlayer;
    BufferedWriter WritePlayer;
    int playerNum;
    private int thisPlayerId;
    public LoginWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        UserName = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        PassWord = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        Register = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        UserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UserName.setForeground(new java.awt.Color(0, 255, 51));
        UserName.setText("USER NAME");
        getContentPane().add(UserName);
        UserName.setBounds(160, 180, 200, 29);

        UserNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserNameField);
        UserNameField.setBounds(360, 180, 190, 30);

        PassWord.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PassWord.setForeground(new java.awt.Color(51, 255, 51));
        PassWord.setText("PASSWORD");
        getContentPane().add(PassWord);
        PassWord.setBounds(160, 240, 160, 40);

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordField);
        PasswordField.setBounds(360, 250, 190, 30);

        Register.setBackground(new java.awt.Color(0, 0, 0));
        Register.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Register.setForeground(new java.awt.Color(204, 0, 204));
        Register.setText("REGISTER");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(Register);
        Register.setBounds(220, 330, 125, 31);

        Login.setBackground(new java.awt.Color(0, 0, 0));
        Login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Login.setForeground(new java.awt.Color(204, 0, 204));
        Login.setText("LOGIN");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login);
        Login.setBounds(440, 330, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/login.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 890, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameFieldActionPerformed
        // TODO add your handling code here:
        userName=evt.getActionCommand();
    }//GEN-LAST:event_UserNameFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
        //passWord=evt.getActionCommand();
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        userName=UserNameField.getText();
        
        passWord=PasswordField.getPassword();
        if (isPlayerExist()){
            

            this.dispose();
            EventQueue.invokeLater(new Runnable(){
                public void run(){
                    JFrame app=new JFrame();
            
                    final ClientFinal n=new ClientFinal("192.168.79.62",userName);
                    //NewClient n=new NewClient();
                    app.add(n);
                    JMenuBar MenuBar = new javax.swing.JMenuBar();
                    //set Menu
                    
                    JMenu Help=new JMenu();
                    Help.setText("Help");
                    JMenu Us=new JMenu();
                    Us.setText("About Us");
                    JMenu tutorial=new JMenu();
                    tutorial.setText("HOW TO PLAY?");
                    
                    MenuBar.add(Help);
                    Help.add(Us);
                    Help.add(tutorial);
                    
                    Us.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        
                        new aboutUs().setVisible(true);
                    }
                     });
                    
                    tutorial.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        new tutorial().setVisible(true);
                    }
                     });
                    
                    app.setJMenuBar(MenuBar);
                    app.setSize(1400, 850);
                    app.setVisible(true);
                    app.setDefaultCloseOperation(EXIT_ON_CLOSE);
                    
                    app.addWindowListener(new WindowAdapter(){
                        public void windowClosing(WindowEvent e){
                            Formatter x=n.getOutput();
                            x.format("closed\n");
                            x.flush();
                        }
                    });
                    
                }
            });
    
        }
        else{
            JOptionPane.showMessageDialog(null,"Please Register First!\n");
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
           // TODO add your handling code here:
       
        if (isPlayerExist()){
            JOptionPane.showMessageDialog(null,"Already Exis!!\n please Login\n");
        }
        else{
            try {
                    fileWriter=new FileWriter(fileName,true);
                 
                    WritePlayer=new BufferedWriter(fileWriter);
                    System.out.println(userName);
                    WritePlayer.write(userName);
                    WritePlayer.newLine();
                   
                    WritePlayer.write(Arrays.toString(passWord));
                    WritePlayer.newLine();
                    thisPlayerId=playerNum+1;
                    WritePlayer.close();
                    
                    JOptionPane.showMessageDialog(null,"Successfully Registered!\n");
                }
                catch(IOException io){
                    io.printStackTrace();
                }
        }
        
    }//GEN-LAST:event_RegisterActionPerformed
    
    
    public boolean isPlayerExist()
    {
        boolean found=false;
        userName=UserNameField.getText();
        
        passWord=PasswordField.getPassword();
        //open file for reading
        
         try {
            fileReader=new FileReader(fileName);
            ReadPlayer=new BufferedReader(fileReader);
        } 
        catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
         
        String line;
        try {
           
            String name,pass;
           
            int i=1;
            do
            {
                line=ReadPlayer.readLine();
                if (line==null) break;
                name=line;
                line=ReadPlayer.readLine();
                pass=line;
               
                if (userName.equals(name) && Arrays.toString(passWord).equals(pass))
                {
                    thisPlayerId=i;
                    
                    playerNum=i;
                    found=true;
                    break;
                }
                i++;
            }
            while(line!=null);
            ReadPlayer.close();
            
        }
        catch(IOException io){
            io.printStackTrace();
        }
        return found;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JLabel PassWord;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton Register;
    private javax.swing.JLabel UserName;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
